return {
  {
    id=1,
    name="Gay bong chay",
    image="gameres|asset/Texture/Gui/0.png",
    materia={
      {
        type="Material",
        id=0,
        count=10
      },
      {
        type="Material",
        id=1,
        count=5
      },
      {
        type="Material",
        id=2,
        count=5
      }
    }
  },
  {
    id=2,
    name="Gay bong chay",
    image="gameres|asset/Texture/Gui/0.png",
    materia={
      {
        type="Material",
        id=0,
        count=10
      },
      {
        type="Material",
        id=1,
        count=5
      },
      {
        type="Material",
        id=2,
        count=5
      },
      {
        type="Material",
        id=2,
        count=5
      }
    }
  },
  {
    id=3,
    name="Gay bong chay",
    image="gameres|asset/Texture/Gui/0.png",
    materia={
      {
        type="Material",
        id=0,
        count=10
      },
      {
        type="Material",
        id=1,
        count=5
      },
      {
        type="Material",
        id=2,
        count=5
      }
    }
  }
  
}